replacements:
  # Yazım sabitleme örnekleri
  - pattern: "\\bön\\s*olay\\b"
    replace: "ön onay"
  - pattern: "\\bön\\s*anay\\b"
    replace: "ön onay"
  - pattern: "Agentür\\s*F[üu]hrer\\s*Arb[ae]yt"
    replace: "Agentur für Arbeit"
  - pattern: "Agentür\\s*F[üu]hrer\\s*Arbeit"
    replace: "Agentur für Arbeit"
  - pattern: "Agentur\\s*f[üu]r\\s*Arbayt"
    replace: "Agentur für Arbeit"
  - pattern: "\\b[İI]data\\b"
    replace: "İdata"
  - pattern: "\\biy[ıi]\\s*data\\b"
    replace: "İdata"
  - pattern: "\\biy[ıi]\\s*dataya\\b"
    replace: "İdata'ya"
  - pattern: "\\biy[ıi]\\s*datadan\\b"
    replace: "İdata'dan"
  - pattern: "\\biy[ıi]\\s*datada\\b"
    replace: "İdata'da"
  - pattern: "\\biy[ıi]\\s*datayı\\b"
    replace: "İdata'yı"
  - pattern: "ana bin çıktısı"
    replace: "Anabin çıktısı"
  - pattern: "\\bzap\\s*denkli(ğ|g)i\\b"
    replace: "ZAB denkliği"
  - pattern: "iyi\\s*data|iy\\s*data"
    replace: "İdata"

strip_patterns:
  - "^Kaynak:.*$"
  - "^\\s*(merhaba(lar)?|selam(lar)?).*$"
  - "abone ol(mayı)?|beğen(meyi)?|kanal(ı|ımıza)|takip etmeyi"
  - "flash\\s*flash"
  - "(görüşürüz|teşekkürler|izlediğiniz için teşekkürler).*"
  - "sanal değil gerçek ofis"
  - "(çayını|kahveni) içersin"
  - "altyazı.*$"

protected_terms:
  - "Agentur für Arbeit"
  - "İdata"
  - "§81a"
  - "81A"
  - "Anabin"
  - "ZAB"


